### ISSUE TITLE
This mod is INCREDIBLY UNDERRATED!

### ISSUE THREAD

**Issue by DamageMaximo** [Hoo-Knows/HollowKnight.LostArtifacts#1]
Holy sh3t I had no idea something like this was even possible, this is incredible, the modding community is going places, but could you please tell me if there's any risk of corrupting a save file if I accidentally load a one where I had previously used the mod but without the mod enabled?

**Comment by DamageMaximo** [comment]
I see, I would also like to report what I believe to be a bug, when I was using Noxious Shroom in the colosseum of fools, whenever it spread the cloud would not spawn at another enemy's location, but randomly nearby the fog first fog.
Also, Lush Moss is very OP when put in the head slot and being overcharged, especially when combined with Paving Stone and Quick Slash, it makes face-tanking an actually viable strategy, if combined with Stalwart Shell it makes it very easy to not die.

**Comment by Hoo-Knows** [comment]
Lush Moss has been nerfed slightly in the latest update, and Noxious Shroom could be targeting dead enemies which should be fixed in the next update.
