### ISSUE TITLE
Ultrawide Support

### ISSUE THREAD

**Issue by Drexl** [Hoo-Knows/HollowKnight.LostArtifacts#3]
I'd appreciate a patch to support 21:9 ultra-wide. Here is the UI at 3440x1440
![image](https://user-images.githubusercontent.com/2714403/200121184-80ada6a3-f772-4560-80ea-2da8a26632c1.png)

**Comment by Hoo-Knows** [comment]
Hello, apologies for not getting to this sooner. I've made a new release, could you check if it fixes the UI on ultrawide?

**Comment by Drexl** [comment]
I'm in the process of moving right now, but when that's finished and I've got all the machines set back up again I'll check it out. Thanks. :)

**Comment by Drexl** [comment]
Frustratingly, I'm not able to test this now. I switched back to 16:9 as I was more willing to deal w/ the lower resolution than I was the UI issue, but now I can't get 3440x1440 to work after patching Assembly-CSharp.dll. Not sure why it worked before, but isn't now. So, I guess thanks for trying to fix it. I honestly wasn't expecting a response, but it's much appreciated all the same. I'll keep trying to get 21:9 to work again, and let you know how it goes if I do.

**Comment by Hoo-Knows** [comment]
Alright, I'll close the issue for now then. Thanks!
