### ISSUE TITLE
Traveler's Garment interaction with dive

### ISSUE THREAD

**Issue by jaydon145** [Hoo-Knows/HollowKnight.LostArtifacts#4]
Attacking immediately after using dive/dark makes the nail do a crazy amount of damage that can kill most bosses in a couple hits. I assume this is because the velocity while diving is really high.

**Comment by Hoo-Knows** [comment]
The scaling of Traveler's Garment has been changed from exponential to linear in the latest release. Hopefully that makes this combo slightly less crazy (but still good). If you could check to confirm that then I'll close this issue.
