### ISSUE TITLE
Remove Default Artifact Locations When Randomizing in Main Item Group

### ISSUE THREAD

**Issue by dastrdly6585** [Hoo-Knows/HollowKnight.LostArtifacts#5]
When the main item group randomization is turned on, the artifacts still spawn at their default new locations.  This sort of defeats the purpose of randomizing them in the main item group since you will be able to guarantee get specific artifacts at their normal places.  

In some cases, it's not even possible to avoid picking them up at the default locations because another check coincides with it.  This issue primarily applies to cases where you randomize boss geo or randomize hunter's journal entries (e.g. Massive Moss Charger and Crystal Guardian could drop a pickup (or two) in addition to the lost artifact depending on what is randomized).

Edit: As a clarification, there are copies of the artifacts that _are_ randomized into the regular main item group locations.  It's just that the normal artifact locations still have their original artifacts and are not removed.

**Comment by Hoo-Knows** [comment]
This issue should now be fixed in the latest release v1.1.1.0
